### ISSUE TITLE
PODBOX stuck after loading vec files

### ISSUE THREAD

**Issue by emspinosa** [OpenPIV/openpiv-podbox#1]
Hello everyone,

I have installed PODBOX in my MATLAB, but when I try to load vec files that I obtained with Insight 4G the toolbox gets stuck and the computer starts thinking indefinitely ... what can cause this problem? any suggestion?

Thanks a lot.
Regards,

E.S.

**Comment by alexlib** [comment]
We need a sample

**Comment by emspinosa** [comment]
Hello, I can't send you a sample here, can I have an email address please?

**Comment by alexlib** [comment]
https://www.dropbox.com/request/DbnHofHh4A7oZQEHQq0R 

use the file requests to upload it to Dropbox

**Comment by emspinosa** [comment]
Dear Alex, I've done it, I've sent just 11 images, I can't load even them... hope you can help me. Thanks...

**Comment by alexlib** [comment]
it works fine on the older Matlab version on Mac OS X: 7.10.0.499 (R2010a)
write me offline to alex dot liberzon at gmail dot com to setup a teamviewer session (remote access to your computer) - I'll be then able to test it directly with your version.

**Comment by alexlib** [comment]
The problem is with the new GUI definitions of Matlab 2015 (a,b?). It is recommended therefore to use older versions of Matlab. 
the workaround is to replace the podbox.m and podbox.fig files with the files in the branch fix2015. It was tested on R2015 version on Windows 64 bit

**Comment by alexlib** [comment]
https://github.com/OpenPIV/openpiv-podbox/tree/fix2015
